- name: Deploy Docker Container
  hosts: azure_vm
  become: true
  tasks:

    # Ensure the directory for Docker app files exists (you can modify this as needed)
    - name: Ensure Docker app directory exists
      file:
        path: /home/azureuser/project/  # This is where your project files are
        state: directory
        mode: '0755'

    # Copy application files (index.html, Dockerfile) to VM
    - name: Copy application files to VM
      copy:
        src: /path/to/local/project/  # Local path where your project is (with Dockerfile and index.html)
        dest: /home/azureuser/project/
        remote_src: no  # This means you're copying from local machine to VM, not from remote to remote

    # Build Docker image
    - - name: Build Docker image
        command: docker build --no-cache -t my-web-app /home/azureuser/project/



    # Stop existing container (if running)
    - name: Stop existing container (if running)
      command: docker stop web-app
      ignore_errors: yes  # Avoid failure if the container does not exist

    # Remove existing container (if exists)
    - name: Remove existing container (if exists)
      command: docker rm web-app
      ignore_errors: yes  # Avoid failure if the container does not exist

    # Run the Docker container
    - name: Run Docker container
      command: docker run -d -p 80:80 --name web-app my-web-app
